FROM node:20-alpine3.22 AS builder
WORKDIR /app
COPY *.json .
RUN npm install --only=production
COPY . .

FROM node:20-alpine3.22 
WORKDIR /app
COPY --from=builder /app /app
RUN addgroup -S roboshop && \
    adduser -S roboshop -G roboshop && \
    chown -R robosho:roboshop /app
ENV REDIS_HOST="redis-cont" \
    CATALOGUE_HOST="catalogue-cont" \
    CATALOGUE_PORT="8080"
EXPOSE 8080
USER roboshop
ENTRYPOINT ["node"]
CMD ["server.js"]