apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/meghashyam-singh/27-8.git
    targetRevision: main
    path: argocd/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true                    # Delete resources removed from git
      selfHeal: true 